type: default-flatpaks
notify: true
system:
  repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
  repo-name: flathub
  repo-title: "Flathub (system-wide)"
  install:
    # internet
    - org.mozilla.firefox
    - org.mozilla.Thunderbird

    # useful utilities
    - org.pipewire.Helvum

    # applications that are fine as flatpaks
    - org.kde.gwenview
    - org.kde.kcalc

user:
  repo-name: flathub-user
  repo-title: "Flathub (user)"
