type: rpm-ostree
repos:
  # prompt
  - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo

  # bibata cursors
  - https://copr.fedorainfracloud.org/coprs/peterwu/rendezvous/repo/fedora-%OS_VERSION%/peterwu-rendezvous-fedora-%OS_VERSION%.repo

  # kwin theme
  - https://download.opensuse.org/repositories/home:paul4us/Fedora_%OS_VERSION%/home:paul4us.repo

  # bazzite repo
  - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%OS_VERSION%/kylegospo-bazzite-fedora-%OS_VERSION%.repo

  # bazzite multilib
  - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite-multilib/repo/fedora-%OS_VERSION%/kylegospo-bazzite-multilib-fedora-%OS_VERSION%.repo

  # rom properties
  - https://copr.fedorainfracloud.org/coprs/kylegospo/rom-properties/repo/fedora-%OS_VERSION%/kylegospo-rom-properties-fedora-%OS_VERSION%.repo
install:
  # console
  - bat
  - duf
  - fastfetch
  - fd-find
  - fzf
  - git-delta
  - lsd
  - neovim
  - ripgrep
  - sd
  - starship
  - tldr
  - zoxide
  - zsh
  
  # audio
  - playerctl
  - pavucontrol-qt

  # applications
  - ark
  - dolphin
  - dolphin-plugins
  - gwenview
  - kalk
  - kate
  - kitty
  - ksystemlog
  - mpv
  - okular

  # libraries
  - qt5-qtwayland
  - qt6-qtwayland
  - gnome-themes-extra
  - kdepim
  - kdepim-addons
  - kdepim-runtime
  - lzip

  # themes
  - papirus-icon-theme
  - bibata-cursor-themes
  - lightly
  - klassy
  - kvantum

  # performance/userspace utilities
  - gamemode
  - gamescope
  - mangohud
  - joystickwake
  - rom-properties-kf5
  - xwiimote-ng
remove:
  - firefox # default firefox removed in favor of flatpak
  - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
