type: rpm-ostree
repos:
  # shell
  - https://copr.fedorainfracloud.org/coprs/atim/nushell/repo/fedora-%OS_VERSION%/atim-nushell-fedora-%OS_VERSION%.repo

  # prompt
  - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo

  # bibata cursors
  - https://copr.fedorainfracloud.org/coprs/peterwu/rendezvous/repo/fedora-%OS_VERSION%/peterwu-rendezvous-fedora-%OS_VERSION%.repo

  # kwin theme
  - https://download.opensuse.org/repositories/home:paul4us/Fedora_%OS_VERSION%/home:paul4us.repo

  # bazzite repo
  - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%OS_VERSION%/kylegospo-bazzite-fedora-%OS_VERSION%.repo

  # bazzite multilib
  - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite-multilib/repo/fedora-%OS_VERSION%/kylegospo-bazzite-multilib-fedora-%OS_VERSION%.repo

  # rom properties
  - https://copr.fedorainfracloud.org/coprs/kylegospo/rom-properties/repo/fedora-%OS_VERSION%/kylegospo-rom-properties-fedora-%OS_VERSION%.repo
install:
  # console
  - bat
  - duf
  - fastfetch
  - fd-find
  - fzf
  - git-delta
  - lsd
  - neovim
  - nushell
  - ripgrep
  - sd
  - starship
  - zoxide
  - zsh
  
  # audio
  - pavucontrol-qt
  - playerctl

  # applications
  - ark
  - dolphin
  - dolphin-plugins
  - kate
  - kitty
  - ksystemlog
  - merkuro
  - mpv
  - waydroid

  # kde related extensions
  - kaccounts-integration
  - kaccounts-providers
  - kdepim
  - kdepim-addons
  - qt5-qtgraphicaleffects
  - qt5-qtquickcontrols2
  - qt5-qtsvg
  - translate-shell

  # podman
  - podman
  - podman-compose
  - podman-tui

  # libraries
  - fontconfig
  - gnome-themes-extra
  - lzip
  - qt5-qtwayland
  - qt6-qtwayland

  # themes
  - bibata-cursor-themes
  - klassy
  - kvantum
  - lightly
  - papirus-icon-theme

  # utilities
  - crontabs
  - gamemode
  - gamescope
  - joystickwake
  - mangohud
  - rom-properties-kf5
  - xwiimote-ng
remove:
  - firefox # default firefox removed in favor of flatpak
  - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
