type: rpm-ostree
repos:
  # shell
  - https://copr.fedorainfracloud.org/coprs/atim/nushell/repo/fedora-%OS_VERSION%/atim-nushell-fedora-%OS_VERSION%.repo

  # prompt
  - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo

  # bazzite repo
  - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%OS_VERSION%/kylegospo-bazzite-fedora-%OS_VERSION%.repo

  # bazzite multilib
  - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite-multilib/repo/fedora-%OS_VERSION%/kylegospo-bazzite-multilib-fedora-%OS_VERSION%.repo
install:
  # console
  - bat
  - duf
  - fastfetch
  - fd-find
  - fzf
  - git-delta
  - lsd
  - neovim
  - nushell
  - ripgrep
  - sd
  - starship
  - zoxide
  - zsh
  
  # audio
  - pavucontrol-qt
  - playerctl

  # kde
  - ark
  - dolphin
  - dolphin-plugins
  - kate
  - ksystemlog
  - merkuro
  - ffmpegthumbs
  - kaccounts-integration
  - kaccounts-providers
  - kdepim
  - kdepim-addons
  - qt5-qtgraphicaleffects
  - qt5-qtquickcontrols2
  - qt5-qtsvg
  - translate-shell
  - power-profiles-daemon

  # terminals
  - kitty
  - contour-terminal
  - wezterm

  # podman
  - podman
  - podman-compose
  - podman-tui

  # libraries
  - fontconfig
  - gnome-themes-extra
  - lzip
  - qt5-qtwayland
  - qt6-qtwayland

  # utilities
  - crontabs
  - gamemode
  - gamescope
  - joystickwake
  - mangohud
  - xwiimote-ng
