type: rpm-ostree
repos:
  # bibata cursors
  - https://copr.fedorainfracloud.org/coprs/peterwu/rendezvous/repo/fedora-%OS_VERSION%/peterwu-rendezvous-fedora-%OS_VERSION%.repo

  # kwin theme
  - https://download.opensuse.org/repositories/home:paul4us/Fedora_%OS_VERSION%/home:paul4us.repo

  # rom properties
  - https://copr.fedorainfracloud.org/coprs/kylegospo/rom-properties/repo/fedora-%OS_VERSION%/kylegospo-rom-properties-fedora-%OS_VERSION%.repo
install:
  # applications
  - mpv
  - waydroid

  # themes
  - bibata-cursor-themes
  - klassy
  - kvantum
  - lightly
  - papirus-icon-theme

  # utilities
  - rom-properties-kf5
remove:
  - firefox # default firefox removed in favor of flatpak
  - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
