type: yafti
custom-flatpaks:
  # KDE apps
  - Clock: org.kde.kclock
  - Filelight: org.kde.filelight
  - Kamoso: org.kde.kamoso
  - KFind: org.kde.kfind
  - Okular: org.kde.okular
  - Weather: org.kde.kweather

  # system
  - Deja Dup Backups: org.gnome.DejaDup
  - Flatseal (Permission Manager): com.github.tchx84.Flatseal
  - Font Downloader: org.gustavoperedo.FontDownloader

  # internet
  - qBittorrent: org.qbittorrent.qBittorrent
  - NewsFlash: io.gitlab.news_flash.NewsFlash
  - Nicotine+: org.nicotine_plus.Nicotine
  - Wireshark: org.wireshark.Wireshark
    
  # chat
  - Gajim: org.gajim.Gajim
  - nheko: io.github.NhekoReborn.Nheko
  - Revolt: chat.revolt.RevoltDesktop
  - Signal Desktop: org.signal.Signal
  - Vesktop (Discord): dev.vencord.Vesktop

  # gaming
  - Dolphin Emulator: org.DolphinEmu.dolphin-emu
  - DOSBox Staging: io.github.dosbox-staging
  - Gamescope (Utility): org.freedesktop.Platform.VulkanLayer.gamescope
  - MangoHUD (Utility): org.freedesktop.Platform.VulkanLayer.MangoHud//22.08
  - Prism Launcher (Minecraft): org.prismlauncher.PrismLauncher
  - ProtonUp-Qt: net.davidotek.pupgui2
  - RetroArch: org.libretro.RetroArch
  - Steam: com.valvesoftware.Steam
  - Vinegar (Roblox): org.vinegarhq.Vinegar

  # office
  - LibreOffice: org.libreoffice.LibreOffice
  - Obsidian: md.obsidian.Obsidian

  # utilities
  - Bitwarden: com.bitwarden.desktop
  - Bottles: com.usebottles.bottles
  - Gstreamer for OBS: com.obsproject.Studio.Plugin.Gstreamer
  - Gstreamer VAAPI for OBS: com.obsproject.Studio.Plugin.GStreamerVaapi
  - HandBrake: fr.handbrake.ghb
  - OBS Studio: com.obsproject.Studio
  - Okteta: org.kde.okteta
  - VkCapture for OBS: com.obsproject.Studio.OBSVkCapture
