# image will be published to ghcr.io/sernik-tech/<name>
name: sneexys-slice
# description will be included in the image's metadata
description: personal image for Sneexy

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # put some files in the image
  - from-file: sneexy/common/files.yml

  # installs default repositories and rpm-ostree packages
  - from-file: sneexy/common/rpm-ostree.yml

  # installs default repositories and flatpak packages
  - from-file: sneexy/common/flatpaks.yml

  # configure what to pull in from ublue-os/bling
  - from-file: sneexy/common/bling.yml

  # install fonts
  - from-file: sneexy/common/fonts.yml

  # uBlue akmods. includes custom drivers and stuff
  - from-file: sneexy/common/akmods.yml

  # post setup/installer helper gui
  - from-file: sneexy/common/yafti.yml

  # scripts to run post-image creation
  - from-file: sneexy/common/script.yml
