# https://github.com/ublue-os/bling/tree/main/modules/rpm-ostree
type: rpm-ostree
install:
  - gnome-console
remove:
  - gnome-classic-session
  - gnome-software-rpm-ostree
  - gnome-terminal
  - gnome-terminal-nautilus
  - firefox # default firefox removed in favor of flatpak
  - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems