# image will be published to ghcr.io/sernik-tech/<name>
name: sernik-silverblue
# description will be included in the image's metadata
description: Small description of your image, can be a single character if you don't want to fill this out

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module

# Refer to https://universal-blue.org/tinker/modules/ to know more about these.
#
# Note that this reads directly from the `config` folder. So the file structure here should be "your_username/<other_folder_if_required>/common.yml"
modules:
  # Put files inside of the image
  - from-file: example/silverblue/common/files.yml

  # Installs default repositories and rpm-ostree packages
  - from-file: example/silverblue/rpm-ostree.yml

  # Installs default repositories and Flatpak packages
  - from-file: example/silverblue/common/flatpaks.yml

  # Configure what to pull in from ublue-os/bling
  # Optional. Can be removed from here if preferred.
  - from-file: example/silverblue/common/bling.yml

  # Install fonts
  # Optional. Can be removed from here if preferred.
  - from-file: example/silverblue/common/fonts.yml

  # uBlue akmods. Includes custom drivers and stuff
  # Optional. Can be removed from here if preferred.
  - from-file: example/silverblue/common/akmods.yml

  # Post setup/Application installer helper GUI
  # Optional. Can be removed from here if preferred.
  - from-file: example/silverblue/common/yafti.yml

  # Scripts to run post-image creation
  # WARNING: Should not be removed. A required script is ran for image creation.
  - from-file: example/silverblue/common/script.yml
