# image will be published to ghcr.io/sernik-tech/<name>
name: sernik-silverblue
# description will be included in the image's metadata
description: Sernik's Silverblue Template image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module

# Refer to https://universal-blue.org/tinker/modules/ to know more about these.
#
# Note that this reads directly from the `config` folder. So the file structure here should be "common/<your_username>/<common>.yml"
modules:
  # Put files inside of the image
  - from-file: common/example/silverblue/files.yml

  # Installs default repositories and rpm-ostree packages
  - from-file: common/example/silverblue/rpm-ostree.yml

  # Installs default repositories and Flatpak packages
  - from-file: common/example/silverblue/flatpaks.yml

  # Configure what to pull in from ublue-os/bling
  # Optional. Can be removed from here if preferred.
  - from-file: common/example/silverblue/bling.yml

  # Install fonts
  # Optional. Can be removed from here if preferred.
  - from-file: common/example/silverblue/fonts.yml

  # uBlue akmods. Includes custom drivers and stuff
  # Optional. Can be removed from here if preferred.
  - from-file: common/example/silverblue/akmods.yml

  # Post setup/Application installer helper GUI
  # Optional. Can be removed from here if preferred.
  - from-file: common/example/silverblue/yafti.yml

  # Scripts to run post-image creation
  # Commented out because there are no scripts.
  # - from-file: common/example/silverblue/script.yml

  # This sets up the proper policy & signing files for signed images to work fully
  # It's recommended *not* to remove this.
  - type: signing