type: rpm-ostree
repos:
    # swaync
    - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-%OS_VERSION%/erikreider-SwayNotificationCenter-fedora-%OS_VERSION%.repo

    # hyprland
    - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo

    # nwg-shell and friends
    - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-fedora-%OS_VERSION%.repo

    # albert
    - https://download.opensuse.org/repositories/home:manuelschneid3r/Fedora_%OS_VERSION%/home:manuelschneid3r.repo

    # wezterm
    - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo
install:
# sddm, currently commented because of boot issues
    - sddm
    - sddm-wayland-generic

# environment
    - xorg-x11-server-Xwayland
    - polkit
    - lxpolkit
    - xdg-user-dirs
    - dbus-tools
    - dbus-daemon
    - wl-clipboard
    - gnome-keyring
    - pavucontrol
    - playerctl
    - qt5-qtwayland
    - qt6-qtwayland
    - vulkan-validation-layers
    - vulkan-tools
    - google-noto-emoji-fonts
    - gnome-disk-utility

# sound
    - wireplumber
    - pipewire
    - pamixer

# networking
    - network-manager-applet
    - NetworkManager-openvpn
    - NetworkManager-openconnect
    - bluez
    - bluez-tools
    - blueman

# hyprland & utilities
    - hyprland
    - xdg-desktop-portal-hyprland
    - xdg-desktop-portal-gtk
    - hyprland-plugins
    - hyprpicker
    - hypridle
    - hyprlock
    - wofi
    - swww
    - swaync
    - waybar
    - wlogout
    - cliphist
    - nwg-clipman
    - albert

# file manager
    - thunar
    - thunar-archive-plugin
    - thunar-volman
    - xarchiver
    - imv
    - p7zip
    - unrar-free

# screenshot
    - slurp
    - grim
    - hyprshot

# display
    - wlr-randr
    - wlsunset
    - grimshot
    - light
    - swaylock
    - swayidle
    - kanshi
    - nwg-displays

# terminals
    - kitty
    - wezterm
    - contour-terminal
    - qt5-qtgraphicaleffects

# themes and GUI
    - qt5ct
    - qt6ct
    - gnome-themes-extra
    - gnome-icon-theme
    - papirus-icon-theme
    - plasma-breeze
